name: brain-diffuser
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=2.2.2
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - pillow
  - nibabel
  - ipykernel  # Added for Jupyter support
  - jupyter  # Added for complete Jupyter support
  - notebook  # Added for Jupyter Notebook interface
  - pip:
    - absl-py>=1.3.0
    - antlr4-python3-runtime>=4.8
    - anyio>=3.6.2
    - openai-clip
    - einops>=0.3.0
    - fire>=0.4.0
    - ftfy>=6.1.1
    - huggingface-hub>=0.11.0
    - kornia>=0.6.8
    - lpips>=0.1.3
    - opencv-python>=4.5.1.48
    - omegaconf>=2.1.1
    - transformers>=4.19.2
    - tensorboardx>=2.1